#!/bin/bash

# Parse the environment variables and auto-create the default.vcl file
/parse /etc/varnish/default

# Start varnish and log
varnishd -f /etc/varnish/default.vcl -s malloc,100M -a 0.0.0.0:${VARNISH_PORT}
varnishlog